site_name: ASL3 Manual
site_url: https://allstarlink.github.io/
site_description: ASL3 documentation project.
site_author: AllStarLink Team
nav:
  - Home: index.md
  - User Guide:
    - User's Guide: user-guide/index.md
    - Installation: user-guide/install.md
    - Pi Step-by-Step: user-guide/pi-detailed.md
    - ASL Menu: user-guide/menu.md
    - ASL Commands: user-guide/commands.md
    - Configuration: user-guide/config.md
  - Developer Guide:
    - Package Builds : developers/package-builds.md
