site_name: ASL3
site_url: https://allstarlink.github.io/
site_description: ASL3 documentation project.
site_author: AllStarLink Team
plugins:
  - search
#  - print-site
copyright: Copyright &copy; 2024 AllStarLink, Inc
nav:
  - Home: index.md
  - User Guide:
    - user-guide/index.md
    - user-guide/whats-new.md
    - user-guide/pi-detailed.md
    - user-guide/install.md
    - user-guide/menu.md
    - user-guide/updates.md
    - user-guide/known-issues.md
  - Pi Appliance:
    - pi/index.md
    - pi/cockpit-basics.md
    - pi/cockpit-console.md
    - pi/cockpit-network.md
    - pi/cockpit-updates.md
    - pi/cockpit-services.md
    - pi/cockpit-firewall.md
  - Advanced Topics:
    - adv-topics/index.md
    - adv-topics/commands.md
    - adv-topics/usbinterfaces.md
    - adv-topics/conftmpl.md
    - adv-topics/httpreg.md
    - adv-topics/allowdenylists.md
    - adv-topics/sip-phone.md
    - adv-topics/incompatibles.md
    - adv-topics/broadcastify.md
  - Developer Guide:
    - developers/index.md
    - developers/package-builds.md
    - developers/source-install.md
    - developers/aptly.md
