site_name: ASL3
site_url: https://allstarlink.github.io/
site_description: ASL3 documentation project.
site_author: AllStarLink Team
nav:
  - Home: index.md
  - User Guide:
    - user-guide/index.md
    - user-guide/install.md
    - user-guide/pi-detailed.md
    - user-guide/menu.md
    - user-guide/commands.md
    - user-guide/config.md
    - user-guide/incompatibles.md
    - user-guide/sip-phone.md
    - user-guide/broadcastify.md
  - Developer Guide:
    - developers/index.md
    - developers/package-builds.md
    - developers/source-install.md
    - developers/aptly.md
